# tasks file for jenkins
- name: install wget
  apt:
    name: wget
    state: present


- name: install openjdk
  apt:
    update_cache: no
    name: openjdk-11-jdk
    state: present


- name: import jenkins key
  apt_key:
    state: present
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key


- name: ensure the repository is configured
  apt_repository:
    repo : deb https://pkg.jenkins.io/debian-stable binary/
    state: present
    update_cache: yes


- name: install jenkins
  apt:
    name: jenkins
    state: present
    

- name: start jenkins
  systemd:
    name: jenkins
    state: started


- name: enable jenkins
  systemd:
    name: jenkins
    enabled: true


- name: sleep for 10 seconds and continue with play
  wait_for: timeout=10
  delegate_to: localhost


- name: init password jenkin
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: result


- name: print init admin password for jenkins
  debug:
    var: result.stdout