all:
  children:
    localhost:
      hosts:
        10.154.0.30: #local vm ip address
    node-1:
      hosts:      
        10.154.0.27: #node 1 
    node-2:
      hosts:
        10.154.0.25: #node 2
    node-3:
      hosts:
        10.154.0.28: #node 3
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: d_walker0357 #username if using jenkins use jenkins
    ansible_ssh_private_key_file: '~/.ssh/id_rsa_bastion' # copied private rsa key from the bastion server
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q d_walker0357@10.154.0.29"' # ssh proxy for user@bastion-ip